import { useState, useEffect } from 'react';
import { fetchData } from '../utils/fetchData';

const useMedia = () => {
  const [mediaArray, setMediaArray] = useState([]);

  useEffect(() => {
    const getMedia = async () => {
      try {
        const mediaData = await fetchData(import.meta.env.VITE_MEDIA_API + '/media');
        const mediaWithUser = await Promise.all(
          mediaData.map(async (item) => {
            const userData = await fetchData(
              import.meta.env.VITE_AUTH_API + '/users/' + item.user_id
            );
            return { ...item, username: userData.username };
          })
        );
        setMediaArray(mediaWithUser);
      } catch (error) {
        console.error('Failed to fetch media:', error);
      }
    };
    getMedia();
  }, []);
  
  const postMedia = async (fileData, inputs, token) => {
    // TODO: create a suitable object for Media API: without media_id, user_id, thumbnail and created_at. All those are generated by the API. See the media API documentation.
    const mediaItem = {
      title: inputs.title,
      description: inputs.description,
      filename: fileData.data.filename,
      media_type: fileData.data.media_type,
      filesize: fileData.data.filesize,
    };
    // TODO: post the data to Media API and get the data as MediaResponse
    const options = {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: 'Bearer ' + token,
      },
      body: JSON.stringify(mediaItem),
    };

    const mediaResult = await fetchData(
      import.meta.env.VITE_MEDIA_API + '/media',
      options
    );

    return mediaResult;
  
    // TODO: return the data
};
  return { mediaArray, postMedia}
};

const useAuthentication = () => {
  const postLogin = async (inputs) => {
    const fetchOptions = {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(inputs),
    };
    return await fetchData(import.meta.env.VITE_AUTH_API + '/auth/login', fetchOptions);
  };

  return { postLogin };
};

const useUser = () => {
  const getUserByToken = async (token) => {
    const fetchOptions = {
      headers: {
        Authorization: 'Bearer ' + token,
      },
    };
    return await fetchData(import.meta.env.VITE_AUTH_API + '/users/token', fetchOptions);
  };

  const postUser = async (inputs) => {
    const fetchOptions = {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(inputs),
    };
    return await fetchData(import.meta.env.VITE_AUTH_API + '/users', fetchOptions);
  };

  return { getUserByToken, postUser };
};

const useFile = () => {
  const postFile = async (file, token) => {
    const formData = new FormData();
    formData.append('file', file);

    const options = {
      method: 'POST',
      headers: {
        Authorization: 'Bearer ' + token,
      },
      body: formData,
    };
    const response = await fetchData(
      import.meta.env.VITE_UPLOAD_SERVER + '/upload',
      options);
      return response;
      }
    return { postFile };
}

export { useMedia, useAuthentication, useUser, useFile };